### ISSUE TITLE
KeyBoardView

### ISSUE THREAD

**Issue by thundeGG** [Jay-huangjie/EasyKeyBoardView#1]
MyKeyboard在recyclerview里不弹出键盘

**Comment by thundeGG** [comment]
mKeyboardView和mKeyboard都是null

**Comment by Jay-huangjie** [comment]
@7hundeR 等于null的话我想问题应该出在onDetachedFromWindow这个方法上，因为在回收的时候没有考虑到在recycler上加载的情况,所以导致第二个item使用mKeyboardView等参数都是空的,你可以暂时把onDetachedFromWindow方法注释掉，我抽时间完善一下

**Comment by thundeGG** [comment]
好的  我试试  感谢

**Comment by thundeGG** [comment]
onDetachedFromWindow方法注释掉可以显示出键盘了，但是底下的item会被遮住

**Comment by Jay-huangjie** [comment]
@7hundeR 你是说底部的item不会被顶上去是吗?我刚刚模拟了一下在recyclerview中弹出键盘的情况，没有出现遮挡的问题。那个和onDetachedFromWindow方法没关系，顶布局的方法在showKeyboard方法里，你可以检查下里面的mDecorView和mContentView是不是空的，或者scrolldis参数是否有值，来定位一下bug具体出现在哪里

**Comment by thundeGG** [comment]
好的 我查看一下，大周末的还打扰您，哈哈 ，感谢感谢
