### ISSUE TITLE
请问键盘的背景颜色不能改吗

### ISSUE THREAD

**Issue by runtudecha** [Jay-huangjie/EasyKeyBoardView#11]
请问键盘的背景颜色不能改吗

**Comment by Jay-huangjie** [comment]
可以通过keyDrawable属性指定drawable文件更改

**Comment by runtudecha** [comment]
keyDrawable好像只能改按钮的背景，按钮后面的背景是否能修改呢？

**Comment by Jay-huangjie** [comment]
不是太明白按钮后面的背景是指哪里，你是说那按钮之间的线?

**Comment by runtudecha** [comment]
![image](https://user-images.githubusercontent.com/31232167/116195619-0a396080-a765-11eb-8f63-c46b5791ac26.png)
我把按钮中间做了一点间距

**Comment by Jay-huangjie** [comment]
调用getKeyboardView().setBackgroundColor  试试吧

**Comment by runtudecha** [comment]
成了，谢谢老哥
